"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "react-hot-toast";
import { RecoilRoot } from "recoil";
// const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body>
				{/* <body className={inter.className}> */}

				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
				<RecoilRoot>	{children}</RecoilRoot>
				</ThemeProvider>
				<Toaster />
			</body>
		</html>
	);
}
